apiVersion: v1
kind: Service
metadata:
  name: albushra-redis
  labels:
    app: albushra-redis
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: redis
  selector:
    app: albushra-redis
