apiVersion: apps/v1
kind: Deployment
metadata:
  name: albushra-redis
  labels:
    app: albushra-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: albushra-redis
  template:
    metadata:
      labels:
        app: albushra-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: albushra-redis
spec:
  selector:
    app: albushra-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  type: ClusterIP
